import { useState } from 'react';
import { Download, FileText, FileSpreadsheet, X, Printer } from 'lucide-react';

export interface ExportDataPayload {
  title: string;
  headers: string[];
  rows: (string | number)[][];
  orgName?: string;
  generatedBy?: string;
}

export function ExportCenterModal({
  isOpen,
  onClose,
  dataPayload
}: {
  isOpen: boolean;
  onClose: () => void;
  dataPayload: ExportDataPayload;
}) {
  const [selectedFormat, setSelectedFormat] = useState<'csv' | 'excel' | 'pdf'>('csv');
  const [isExporting, setIsExporting] = useState(false);

  if (!isOpen) return null;

  const handleExecuteExport = () => {
    setIsExporting(true);

    setTimeout(() => {
      const now = new Date().toISOString().split('T')[0];
      const filename = `${dataPayload.title.toLowerCase().replace(/\s+/g, '_')}_export_${now}`;

      if (selectedFormat === 'csv' || selectedFormat === 'excel') {
        // Generate CSV content with BOM for Excel UTF-8 compatibility
        const csvRows = [
          [`AssetFlow ERP — ${dataPayload.title}`],
          [`Organization: ${dataPayload.orgName || 'AssetFlow Enterprise'}`, `Generated By: ${dataPayload.generatedBy || 'Admin'}`, `Date: ${new Date().toLocaleString()}`],
          [], // Empty row
          dataPayload.headers,
          ...dataPayload.rows
        ];

        const csvContent = '\uFEFF' + csvRows.map(e => e.map(val => `"${String(val ?? '').replace(/"/g, '""')}"`).join(',')).join('\n');
        const blob = new Blob([csvContent], { type: selectedFormat === 'excel' ? 'application/vnd.ms-excel;charset=utf-8;' : 'text/csv;charset=utf-8;' });
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = `${filename}.${selectedFormat === 'excel' ? 'xlsx' : 'csv'}`;
        link.click();
      } else if (selectedFormat === 'pdf') {
        // Trigger browser printable view with AssetFlow report template header
        const printWindow = window.open('', '_blank');
        if (printWindow) {
          const html = `
            <!DOCTYPE html>
            <html>
            <head>
              <title>${dataPayload.title} — AssetFlow ERP Report</title>
              <style>
                body { font-family: system-ui, -apple-system, sans-serif; margin: 30px; color: #0f172a; }
                .header { border-bottom: 2px solid #4f46e5; padding-bottom: 16px; margin-bottom: 24px; display: flex; justify-content: space-between; items: center; }
                .title { font-size: 24px; font-weight: 800; color: #4f46e5; }
                .meta { font-size: 11px; color: #64748b; margin-top: 4px; }
                table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 12px; }
                th { background-color: #f8fafc; border: 1px solid #cbd5e1; padding: 10px; text-align: left; font-weight: 700; text-transform: uppercase; font-size: 10px; color: #475569; }
                td { border: 1px solid #cbd5e1; padding: 8px 10px; }
                tr:nth-child(even) { background-color: #f8fafc; }
                .footer { margin-top: 32px; border-top: 1px solid #e2e8f0; padding-top: 12px; text-align: center; font-size: 10px; color: #94a3b8; }
              </style>
            </head>
            <body>
              <div class="header">
                <div>
                  <div class="title">AssetFlow ERP — ${dataPayload.title}</div>
                  <div class="meta">Organization: ${dataPayload.orgName || 'AssetFlow Enterprise'} | Generated By: ${dataPayload.generatedBy || 'Admin'} | Date: ${new Date().toLocaleString()}</div>
                </div>
              </div>
              <table>
                <thead>
                  <tr>${dataPayload.headers.map(h => `<th>${h}</th>`).join('')}</tr>
                </thead>
                <tbody>
                  ${dataPayload.rows.map(r => `<tr>${r.map(c => `<td>${c ?? ''}</td>`).join('')}</tr>`).join('')}
                </tbody>
              </table>
              <div class="footer">
                Official Confidential Export Generated by AssetFlow ERP System &copy; 2026
              </div>
              <script>window.onload = function() { window.print(); }</script>
            </body>
            </html>
          `;
          printWindow.document.write(html);
          printWindow.document.close();
        }
      }

      setIsExporting(false);
      onClose();
    }, 400);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-zinc-900/60 backdrop-blur-sm" onClick={onClose}>
      <div 
        className="w-full max-w-md bg-white dark:bg-zinc-900 border border-surface-200 dark:border-zinc-800 rounded-2xl shadow-2xl p-6 relative animate-in fade-in zoom-in-95 duration-150"
        onClick={e => e.stopPropagation()}
      >
        <button onClick={onClose} className="absolute top-4 right-4 p-1.5 rounded-lg text-surface-400 hover:text-surface-900 dark:hover:text-white">
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center space-x-3 mb-4">
          <div className="w-10 h-10 rounded-xl bg-brand-50 dark:bg-brand-950/60 border border-brand-200 dark:border-brand-800 flex items-center justify-center text-brand-900 dark:text-brand-400">
            <Download className="w-5 h-5" />
          </div>
          <div>
            <h3 className="font-extrabold text-base text-surface-900 dark:text-white">Export Center</h3>
            <p className="text-xs text-surface-500 dark:text-zinc-400 font-medium">Export {dataPayload.title} with AssetFlow branding</p>
          </div>
        </div>

        <div className="bg-surface-50 dark:bg-zinc-950 p-3 rounded-xl border border-surface-200 dark:border-zinc-800 mb-5 text-xs">
          <div className="font-bold text-surface-800 dark:text-zinc-200 mb-1">{dataPayload.title} Dataset</div>
          <div className="text-surface-500 dark:text-zinc-400 flex justify-between font-mono">
            <span>Total Records: <strong className="text-surface-900 dark:text-white">{dataPayload.rows.length}</strong></span>
            <span>Columns: <strong className="text-surface-900 dark:text-white">{dataPayload.headers.length}</strong></span>
          </div>
        </div>

        {/* Format Selector */}
        <div className="space-y-2 mb-6">
          <label className="text-[10px] font-extrabold uppercase tracking-wider text-surface-500 dark:text-zinc-400">Select Export Format</label>
          <div className="grid grid-cols-3 gap-2">
            {[
              { id: 'csv', name: 'CSV File', ext: '.csv', icon: FileText },
              { id: 'excel', name: 'Excel Sheet', ext: '.xlsx', icon: FileSpreadsheet },
              { id: 'pdf', name: 'PDF Printable', ext: '.pdf', icon: Printer },
            ].map(fmt => {
              const Icon = fmt.icon;
              const isSel = selectedFormat === fmt.id;
              return (
                <button
                  key={fmt.id}
                  onClick={() => setSelectedFormat(fmt.id as any)}
                  className={`p-3 rounded-xl border flex flex-col items-center justify-center space-y-1.5 transition-all cursor-pointer ${
                    isSel 
                      ? 'border-brand-900 bg-brand-50/50 dark:bg-brand-950/40 text-brand-900 dark:text-brand-400 font-bold ring-2 ring-brand-900/20' 
                      : 'border-surface-200 dark:border-zinc-800 hover:bg-surface-50 dark:hover:bg-zinc-800 text-surface-600 dark:text-zinc-400'
                  }`}
                >
                  <Icon className="w-5 h-5" />
                  <span className="text-xs">{fmt.name}</span>
                  <span className="text-[9px] font-mono opacity-60">{fmt.ext}</span>
                </button>
              );
            })}
          </div>
        </div>

        <button
          onClick={handleExecuteExport}
          disabled={isExporting || dataPayload.rows.length === 0}
          className="w-full py-3 rounded-xl bg-brand-900 hover:bg-brand-800 text-white font-bold text-xs shadow-md shadow-brand-900/20 transition-all flex items-center justify-center space-x-2 cursor-pointer disabled:opacity-50"
        >
          {isExporting ? (
            <span>Generating Export...</span>
          ) : (
            <>
              <Download className="w-4 h-4" />
              <span>Download Branded {selectedFormat.toUpperCase()}</span>
            </>
          )}
        </button>
      </div>
    </div>
  );
}
